server:
  port: 8081

jwt:
  secret: HIDDEN
  expiration: 18000000

spring:
  datasource:
    url: jdbc:mysql://localhost/jwt_example?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: HIDDEN
    password: HIDDEN
  jpa:
    hibernate:
      ddl-auto: create-drop
